SELECT * FROM EMPLOYEES
WHERE FIRST_NAME LIKE 'D%'
AND SALARY > 10000;

SELECT * FROM EMPLOYEES
WHERE FIRST_NAME LIKE 'D%'
  AND SALARY > 7000 AND JOB_ID = 'SA_REP';

SELECT * FROM EMPLOYEES
WHERE FIRST_NAME LIKE 'D%'
  OR SALARY > 7000 OR  JOB_ID = 'SA_REP';

SELECT * FROM EMPLOYEES
WHERE NOT (JOB_ID = 'SA_MAN');

SELECT * FROM EMPLOYEES
WHERE LAST_NAME NOT LIKE 'K%';

SELECT * FROM EMPLOYEES
WHERE JOB_ID NOT IN ('SA_MAN', 'ST_CLARK');

SELECT * FROM EMPLOYEES
WHERE SALARY NOT BETWEEN 5000 AND 6500;

SELECT * FROM EMPLOYEES
WHERE COMMISSION_PCT IS NOT NULL;

SELECT * FROM EMPLOYEES
WHERE COMMISSION_PCT IS NOT NULL
      AND LAST_NAME NOT like '%n';