SELECT * FROM EMPLOYEES
WHERE FIRST_NAME like '__n%'
AND COMMISSION_PCT is null;

SELECT * FROM EMPLOYEES
WHERE FIRST_NAME like 'A%'
AND JOB_ID = 'SA_REP';

SELECT * FROM EMPLOYEES
WHERE FIRST_NAME like '__n%' AND COMMISSION_PCT is null
OR (FIRST_NAME like 'A%' AND JOB_ID = 'SA_REP');

SELECT * FROM EMPLOYEES
WHERE FIRST_NAME like '__n%' AND (COMMISSION_PCT is null
OR FIRST_NAME like 'A%') AND JOB_ID = 'SA_REP';

SELECT * FROM EMPLOYEES
WHERE ((FIRST_NAME like '__n%' AND COMMISSION_PCT is null)
OR FIRST_NAME like 'A%') AND JOB_ID = 'SA_REP';

SELECT FIRST_NAME, LAST_NAME, SALARY, DEPARTMENT_ID, JOB_ID, COMMISSION_PCT
FROM EMPLOYEES
WHERE LAST_NAME like '%i%' AND SALARY > EMPLOYEE_ID * 50
OR JOB_ID IN ('IT_PROG', 'PU_CLERK') AND COMMISSION_PCT is null;

SELECT FIRST_NAME, LAST_NAME, SALARY, DEPARTMENT_ID, JOB_ID, COMMISSION_PCT
FROM EMPLOYEES
WHERE LAST_NAME like '%i%'
   OR
      SALARY > EMPLOYEE_ID * 50 AND JOB_ID IN ('IT_PROG', 'PU_CLERK')
   OR
      COMMISSION_PCT is null;