SELECT * FROM EMPLOYEES
WHERE FIRST_NAME ='David';

SELECT * FROM EMPLOYEES
WHERE JOB_ID = 'FI_ACCOUNT';

SELECT FIRST_NAME, LAST_NAME, SALARY, DEPARTMENT_ID
FROM EMPLOYEES
WHERE DEPARTMENT_ID = 50 AND SALARY > 4000;

SELECT * FROM EMPLOYEES
WHERE DEPARTMENT_ID = 20 OR DEPARTMENT_ID = 30;

SELECT * FROM EMPLOYEES
WHERE FIRST_NAME like '_a%a';

SELECT * FROM EMPLOYEES
WHERE COMMISSION_PCT is not null
    AND DEPARTMENT_ID IN (50, 80)
ORDER BY 4;

SELECT * FROM EMPLOYEES
WHERE FIRST_NAME like '%n%n%';

SELECT * FROM EMPLOYEES
WHERE FIRST_NAME like '_____%'
ORDER BY DEPARTMENT_ID DESC nulls last;

SELECT * FROM EMPLOYEES
WHERE SALARY BETWEEN 3000 AND 7000
AND COMMISSION_PCT is null
    AND JOB_ID IN ('PU_CLERK', 'ST_MAN', 'ST_CLERK');

SELECT * FROM EMPLOYEES
WHERE FIRST_NAME like '%\%%' escape '\';

SELECT JOB_ID, FIRST_NAME, SALARY from EMPLOYEES
WHERE EMPLOYEE_ID >= 120 AND  NOT JOB_ID = 'IT_PROG'
ORDER BY JOB_ID, FIRST_NAME DESC;