SELECT * FROM EMPLOYEES
WHERE INSTR(JOB_ID, 'PROG') = 4;

SELECT INSTR('Tasmity Israpilova', 't') FROM dual;

SELECT * FROM EMPLOYEES
WHERE INSTR(HIRE_DATE, '05') = 4;

SELECT * FROM EMPLOYEES
WHERE INSTR(SALARY, '2') = 2;

SELECT INSTR('Tasmity Israpilova', 'a', 2, 3)
FROM dual;
