SELECT MOD(7, 3) FROM dual;

SELECT MOD(8, 3) FROM dual;

SELECT MOD(9, 3) FROM dual;

SELECT MOD(3, 9) FROM dual;

SELECT MOD(0, 3) FROM dual;

SELECT MOD(9, 0) FROM dual;

SELECT MOD(39, 5) FROM dual;

SELECT MOD(-39, 5) FROM dual;

SELECT MOD(3.1, 2) FROM dual;

SELECT MOD(3.1, 2.2) FROM dual;

select * from EMPLOYEES
WHERE MOD(EMPLOYEE_ID, 2) = 0;

SELECT FIRST_NAME, LAST_NAME, EMPLOYEE_ID, MOD(EMPLOYEE_ID, 3) + 1 as Team
FROM EMPLOYEES;


