SELECT EMAIL, SUBSTR(email, 4) FROM EMPLOYEES;

SELECT EMAIL, SUBSTR(email, 4) FROM EMPLOYEES;

SELECT EMAIL, SUBSTR(email, 4, 2) FROM EMPLOYEES;

SELECT EMAIL, SUBSTR(email, 6, 2) FROM EMPLOYEES;

SELECT SUBSTR('privet, kak dela?', 7) FROM dual;

SELECT SUBSTR('privet, kak dela?', 7, 5) FROM dual;

SELECT SALARY, SUBSTR(SALARY, 2, 3) FROM EMPLOYEES;

SELECT HIRE_DATE, SUBSTR(HIRE_DATE, 2, 3) FROM EMPLOYEES;

SELECT SUBSTR('privet, kak dela?', -4) FROM dual;

SELECT SUBSTR('privet, kak dela?', -4, 2) FROM dual;