SELECT SYSDATE FROM dual;

SELECT TO_CHAR(sysdate, 'DD-MM-RR hh24:mi:ss') FROM dual;

SELECT SYSDATE - HIRE_DATE FROM EMPLOYEES;

SELECT SYSDATE - 5 FROM dual;

SELECT SYSDATE + 5 FROM dual;

SELECT SYSDATE, SYSDATE + 5, SYSDATE - 5 FROM dual;
