SELECT * FROM EMPLOYEES
WHERE length(FIRST_NAME) > 10;

SELECT * FROM EMPLOYEES
WHERE mod(SALARY, 1000) = 0;

SELECT PHONE_NUMBER, substr(PHONE_NUMBER, 1, 3)
FROM EMPLOYEES
WHERE PHONE_NUMBER like '___.___.____';

SELECT * FROM EMPLOYEES
WHERE substr(FIRST_NAME, -1) = 'm'  AND length(FIRST_NAME) > 5;

SELECT next_day(sysdate, 5) FROM dual;

SELECT * FROM EMPLOYEES
WHERE months_between(sysdate, HIRE_DATE) > 150;

SELECT replace(PHONE_NUMBER, '.', '_') FROM EMPLOYEES;

SELECT upper(FIRST_NAME), lower(EMAIL), initcap(JOB_ID)
FROM EMPLOYEES;

SELECT concat(FIRST_NAME, SALARY) FROM EMPLOYEES;

SELECT HIRE_DATE, round(HIRE_DATE, 'MM'), TRUNC(HIRE_DATE, 'YYYY')
FROM EMPLOYEES;

SELECT rpad(FIRST_NAME, 10, '$'), lpad(LAST_NAME, 15, '!')
FROM EMPLOYEES;

SELECT FIRST_NAME, instr(FIRST_NAME, 'a', 1,  2) FROM EMPLOYEES;

SELECT  '!!!HELLO!! MY FRIEND!!!!!!!!', trim( '!' from '!!!HELLO!! MY FRIEND!!!!!!!!')
FROM dual;

SELECT SALARY, SALARY * 3.1415, round(SALARY * 3.1415), trunc(salary * 3.1415, -3) / 1000
FROM EMPLOYEES;

SELECT HIRE_DATE, add_months(HIRE_DATE, 6), last_day(HIRE_DATE)
FROM EMPLOYEES;