SELECT LPAD('Tata', 7, '#') FROM dual;

SELECT RPAD('Tata', 7, '#') FROM dual;

SELECT FIRST_NAME, LPAD(FIRST_NAME, 25, '$') FROM EMPLOYEES;

SELECT FIRST_NAME, LPAD(FIRST_NAME, 25, '$'), RPAD(FIRST_NAME, 25, '$') FROM EMPLOYEES;

SELECT FIRST_NAME, LPAD(FIRST_NAME, 25, 'ABC') FROM EMPLOYEES;

SELECT RPAD('Privet', 5, '!') FROM dual;

SELECT SYSDATE, RPAD(SYSDATE, 5, '!') FROM dual;

SELECT RPAD(FIRST_NAME, 15, ' ') || LPAD(SALARY, 8, ' ') FROM EMPLOYEES;