SELECT HIRE_DATE, TRUNC(HIRE_DATE, 'CC') FROM EMPLOYEES
WHERE EMPLOYEE_ID IN (120, 121);

SELECT HIRE_DATE, TRUNC(HIRE_DATE, 'YYYY') FROM EMPLOYEES
WHERE EMPLOYEE_ID IN (120, 121);

SELECT HIRE_DATE, TRUNC(HIRE_DATE, 'MM') FROM EMPLOYEES
WHERE EMPLOYEE_ID IN (120, 121);

SELECT HIRE_DATE, TRUNC(HIRE_DATE, 'Q') FROM EMPLOYEES
WHERE EMPLOYEE_ID IN (120, 121);

SELECT HIRE_DATE, TRUNC(HIRE_DATE, 'DD') FROM EMPLOYEES
WHERE EMPLOYEE_ID IN (120, 121);

SELECT HIRE_DATE, TRUNC(HIRE_DATE) FROM EMPLOYEES
WHERE EMPLOYEE_ID IN (120, 121);